input_list[0]='Surface.js' 
input_list[1]='Surface_map.js' 
input_list[2]='Surface_scat.js' 
input_list[3]='Surface_sign.js' 
input_list[4]='Temp.js' 
input_list[5]='Temp_prof.js' 
input_list[6]='Temp_sign.js' 
